services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "${NGINX_PROXY_PORT_HOST}:${NGINX_PROXY_PORT_CONTAINER}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - nginx
    profiles:
      - main
    container_name: ${NGINX_PROXY_CONTAINER_NAME}

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    networks:
      - nginx
    profiles:
      - main

networks:
  nginx:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
