services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "${NGINX_PROXY_PORT_HOST}:${NGINX_PROXY_PORT_CONTAINER}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - main_certs:/etc/nginx/certs:ro
      - main_vhost:/etc/nginx/vhost.d
      - main_html:/usr/share/nginx/html
    networks:
      - nginx
    profiles:
      - main
    container_name: ${NGINX_PROXY_CONTAINER_NAME}
    labels:
      - com.github.nginx-proxy.nginx

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - main_certs:/etc/nginx/certs
      - main_vhost:/etc/nginx/vhost.d
      - main_html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - NGINX_PROXY_CONTAINER=${NGINX_PROXY_CONTAINER_NAME}
    networks:
      - nginx
    profiles:
      - main
    container_name: ${NGINX_PROXY_ACME_CONTAINER_NAME}

networks:
  nginx:

volumes:
  main_certs:
  main_vhost:
  main_html:
